### ISSUE TITLE
Any plan for personalised content fetching using auth with email&password ?

### ISSUE THREAD

**Issue by Shabinder** [tr1ckydev/spotifly#4]
same as title.

**Comment by tr1ckydev** [comment]
Soon, stay tuned ;)

**Comment by tr1ckydev** [comment]
Working on it. 
I had success with the cookie value to fetch personalised content, don't really have any idea if I can fetch cookie value with email and password.

**Comment by Shabinder** [comment]
I took a brief take on this well, didn't landed anywhere solid then,
but maybe we can discuss and see if something can be done ? 
perhaps a short video call just so we are both upto speed and where do we stand and see how I can contribute in here, as I do want to and get this done, the earlier the better...
and also sunday is here.

**Comment by Shabinder** [comment]
my mail: dev.shabinder@gmail.com
and TG username: @Shabinder

**Comment by tr1ckydev** [comment]
> I took a brief take on this as well, didn't landed anywhere solid then,
> but maybe we can discuss and see if something can be done ? 
> perhaps a short video call just so we are both upto speed and where do we stand and see how I can contribute in here, as I do want to and get this done, the earlier the better...
> and also sunday is here.

Sounds great, will be contacting you on telegram soon.

**Comment by tr1ckydev** [comment]
Added support for it in v0.1.1

**Comment by Shabinder** [comment]
👀 
Improvement: automating cookie generation and capture ?

**Comment by tr1ckydev** [comment]
No plans to support that yet. Also, I had contacted you on Telegram and email but haven't received any response yet.

**Comment by Shabinder** [comment]
Whats ur telegram handle ?

must have got buried down among chats.

**Comment by tr1ckydev** [comment]
It's @tr1ckydev

**Comment by Shabinder** [comment]
Pinged you there.
